name: release
permissions:
    "contents": "write"

on:
    push:
        tags:
            - "v**[0-9]+.[0-9]+.[0-9]+*"
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    CARGO_TERM_COLOR: always

jobs:
    release:
        name: release
        runs-on: macos-latest
        steps:
            - uses: ceejbot/action-rust-releaser@HEAD
              env:
                  HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
                  REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  executable: tomato
                  refname: ${{ github.ref_name }}
                  tap_repo: ceejbot/homebrew-tap
                  tap_email: ceejceej@gmail.com
                  tap_user: formula robot
